export PS1='DOCKER \u@\h:\w> '

export MAKEFLAGS="-j4 -k"

export ROSDIR=/opt/ros/kinetic
source ${ROSDIR}/setup.bash

alias ls="ls -F --color"
alias ll="ls -lFh --color"
alias la="ls -alFh --color"
alias lt="ls -rtlFh --color"
alias lS="ls -rSlFh --color"
alias cp="cp -ipvP"
alias mv="mv -iv"
alias rm="rm -iv"

alias qtcreator='$HOME/local/opt/qtcreator-4.6.1/bin/qtcreator'
