BASE = ../../rai
BASE2 = ../../src

DEPEND = Core Algo Gui Geo KOMO Kin LGP Logic Perception RealSense NewControl Franka LGPop FlatVision opencv_reg RosCom

OBJS = main.o cameraCalibration.o

OPENCV = 1


include $(BASE)/build/generic.mk
