// Generated by gencpp from file robot_msgs/SendJointTrajectory.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_SENDJOINTTRAJECTORY_H
#define ROBOT_MSGS_MESSAGE_SENDJOINTTRAJECTORY_H

#include <ros/service_traits.h>

#include <robot_msgs/SendJointTrajectoryRequest.h>
#include <robot_msgs/SendJointTrajectoryResponse.h>


namespace robot_msgs
{

struct SendJointTrajectory
{

typedef SendJointTrajectoryRequest Request;
typedef SendJointTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendJointTrajectory
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::SendJointTrajectory > {
  static const char* value()
  {
    return "b8ca7270ae29f6a2b069682a8cfd473e";
  }

  static const char* value(const ::robot_msgs::SendJointTrajectory&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::SendJointTrajectory > {
  static const char* value()
  {
    return "robot_msgs/SendJointTrajectory";
  }

  static const char* value(const ::robot_msgs::SendJointTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::SendJointTrajectoryRequest> should match
// service_traits::MD5Sum< ::robot_msgs::SendJointTrajectory >
template<>
struct MD5Sum< ::robot_msgs::SendJointTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::SendJointTrajectory >::value();
  }
  static const char* value(const ::robot_msgs::SendJointTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::SendJointTrajectoryRequest> should match
// service_traits::DataType< ::robot_msgs::SendJointTrajectory >
template<>
struct DataType< ::robot_msgs::SendJointTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::SendJointTrajectory >::value();
  }
  static const char* value(const ::robot_msgs::SendJointTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::SendJointTrajectoryResponse> should match
// service_traits::MD5Sum< ::robot_msgs::SendJointTrajectory >
template<>
struct MD5Sum< ::robot_msgs::SendJointTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::SendJointTrajectory >::value();
  }
  static const char* value(const ::robot_msgs::SendJointTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::SendJointTrajectoryResponse> should match
// service_traits::DataType< ::robot_msgs::SendJointTrajectory >
template<>
struct DataType< ::robot_msgs::SendJointTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::SendJointTrajectory >::value();
  }
  static const char* value(const ::robot_msgs::SendJointTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_SENDJOINTTRAJECTORY_H
